export const district=[
    {
        'name':'ALAPUZHA',
        'image':'alpy.png'
    },
    {
        'name':'ERNAKULAM',
        'image':'erklm.png'
    },
    {
        'name':'IDUKKI',
        'image':'idki.png'
    },
    {
        'name':'KANNUR',
        'image':'Kan.png'
    },
    {
        'name':'KASARAGOD',
        'image':'kasar.png'
    },
    {
        'name':'KOLLAM',
        'image':'klm.png'
    },
    {
        'name':'KOZHOKODE',
        'image':'kozh.png'
    },
    {
        'name':'KOTTAYAM',
        'image':'ktym.png'
    },
    {
        'name':'MALAPURAM',
        'image':'mlprm.png'
    },
    {
        'name':'PALAKAD',
        'image':'plkd.png'
    },
    {
        'name':'PATHANAMTHITTA',
        'image':'ptm.png'
    },
    {
        'name':'THIRUVANANDAPURAM',
        'image':'tvm.png'
    },
    {
        'name':'THRISSUR',
        'image':'trsr.png'
    },
    {
        'name':'WAYANAD',
        'image':'way.png'
    },

]